### ISSUE TITLE
timeseries should include a swagger spec

### ISSUE THREAD

**Issue by MS-ResilienX** [eagle-io/timeseries#1]
I'm implementing a time series interface of my own that is very similar to this. It's a shame because this meets all of my requirements for time series data in json.

**Comment by abonstu** [comment]
what did you have in mind? 

this library defines construction and handling of timeseries data, as far as im aware swagger only deals with RESTful APIs 🤔

**Comment by MS-ResilienX** [comment]
Hi Jarrah. The jts standard is useful, especially given that it is licensed with the MIT license. 

Providing a swagger spec (or at least a json schema) that encapsulates/reflects the jts standard would simply allow a client to integrate with an endpoint that uses that message format. 

I'm writing a swagger spec based on the format, but it would be nice if there was a json schema provided that is unified with the typescript project.

**Comment by abonstu** [comment]
nice one - i haven't used json-schema before.

@nhitchins can you take a look at crafting a json-schema for JTS?

https://json-schema.org/

**Comment by abonstu** [comment]
here's a first pass at a json-schema spec

https://github.com/eagle-io/timeseries/blob/master/jts.schema.json

ideally, schema validation would identify the dataType defined in the column header and assert that all values in the associated data records match this dataType, but i haven't figured out a mechanism to include this functionality.

happy to accept a PR if you can figure it out 😉
